### ISSUE TITLE
Rethink `magit-revert-buffers`

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1547]
- [x] make filename comparison more robust as suggested in #1545
- [x] maybe provide a "whenever magit did something" hook, see #1546
- [x] consider performance implications, see #1549
