### ISSUE TITLE
Fix performance regressions

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1644]
Generally `next` is faster than `master`, but there also are some performance regressions which take effect under certain circumstances.

* [x] `magit-backup-mode` is enabled by default and uses the slow elisp implementation of stashes #1620, #1582 *no longer enabled by default*
* [x] `magit-insert-untracked-files` can be very slow when there are many untracked files #1599
* [ ] washing diffs is *sometimes* very slow, the exact cause has not been determined yet #1581 
* [x] other modes hook into Magit refreshes, make sure users know who is responsible for the slowdown #1547 *unreleased documentation mentions that now*
* [x] calculate commit counts in refs buffer asynchronously #1674 *not async but very easy to disable now*
* [x] `git submodule foreach 'echo $path'` performs horribly. *so we no longer use it*

**Note:** To report another performance regression, please use a new issue dedicated to that.

**Comment by tarsius** [comment]
Since there's only one problem remaining, for which there is a dedicated issue, I am closing this one.
