### ISSUE TITLE
Roadmap for the v2 series

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2180]
For approximate release dates see [milestones](https://github.com/magit/magit/milestones).

----

### DONE [v1.4](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/1.4.0.txt)

> Release something that's half decent and works with ancient Emacs and ancient Git.

### DONE [v2.1](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.1.0.txt)

> Get my work of the last two years out the door.

### DONE [v2.2](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.2.0.txt)

> Deal with regressions and "previously it was better".

### DONE [v2.3](https://github.com/magit/magit/milestones/2.3.0)

> Get rid of the backlog (so that I can later concentrate on the really important things).

- [x] #2186 do more work inside magit-commit-squash-internal
- [x] #2187 add magit-rebase-interactive-1, support rebasing root commits
- [x] [km/checkout-file](https://github.com/magit/magit/compare/km/checkout-file) add magit-checkout-file
- [x] #2191 Implement `magit-branch-reset` and `magit-branch-spinoff`.
- [x] #2193 Quit window without restoring previous window configuration
- [x] #2195 Basic blob navigation
- [x] #2216 Refactor how the revision buffer is created and looks
- [x] #2225 Implement a revision stack for inserting commit descriptions into commit messages and emails
- [x] #2226 Support showing log for the region
- [x] #2227 jump to next block of changed lines after staging region
- [x] #2231 am: don't fail when commit doesn't apply and doesn't already exist in repo (km)
- [x] #2242 Refactor magit-toplevel
- [x] #2243 avoid `git log --graph' inefficiency
- [x] #2259 * magit-git-executable default should be updated for Git for Windows 2.x (np)
- [x] #2271 Allow applying multiple hunks at once
- [x] #2281 Use the "noglob" option on Cygwin and MSYS2 (jm)
- [x] #2282 Give users more control over how buffers are displayed
- [x] #2300 Show update date in reflog margin, don't show author name
- [x] #2311 Try to find the password before asking user (dc)
- [x] #2338 Replace option magit-diff-auto-show with hook functions
- [x] #2348 handle custom cygwin mounts (np)
- [x] #2360 start credential-cache-daemon directly from Emacs (np)

### [v2.4](https://github.com/magit/magit/milestones/2.4.0)

> Deal with the fact that everyone has a different opinion on how branching and pushing should work.

- [x] #2387 stop faking negative overlay property priorities
- [x] #2389 magit-define-popup: add :setup-function and :refresh-function keyword arguments
- [x] #2390 Implement trivial parts of push-remote support
- [x] #2414 Refactor branch handling
- [x] #2419 rebase mode: move line extensions (km)
- [x] #2423 pass dirname to magit--with-safe-default-directory  (np)
- [x] #2447 Make it less likely that the push-remote is undefined
- [x] #2448 Generalize visibility cache
- [x] #2452 magit-pull-or-fetch-popup: new popup
- [x] #2453 Restore magit-push-implicitly, add magit-push-to-remote
- [x] #2458 Allow not limiting reverts to tracked files
- [x] #2474 revert buffers using a globalized variant of auto-revert-mode

----

Enter maintenance mode and eventually start working on v3.

**Comment by tarsius** [comment]
@kyleam are you using `pu`?

**Comment by kyleam** [comment]
Yeah.  I haven't taken the time to deliberately test any of the changes
yet though.

**Comment by tarsius** [comment]
@kyleam I am going to release v2.2.2 in an hour or so. Later today I will merge some of the feature branches into master. km/checkout-file and #2216 I will likely merge today. Possibly #2193 too. And tomorrow or so I would like to merge #2186 and #2187. In each case I will test again and update the documentation and commit messages if necessary. But if you can find some time to test some more that would be great. Let me know if you have any concerns about any of these branches.

**Comment by kyleam** [comment]
I've been using all of these, and I don't think I've encountered any
issues aside from the ones I've already reported.

* #2216 (jb/refactor-revision-buffer)

  I believe the comment below is still an issue.
  https://github.com/magit/magit/commit/a09d5bf5d71959834aaf0c9a2a05ab17e89b2bdb#commitcomment-13040097


* #2193 (pr/quit-window)

  While I think this is fine to merge, I like the old behavior and
  pretty quickly changed magit-bury-buffer-function to get it back, so I
  haven't tested this with the new default too heavily.

* #2186 (jb/refactor-fixup) and #2187 (jb/refactor-rebase)

  I haven't looked at the changes too closely, but I use all rebase
  variants a lot and haven't noticed any issues.  I tested rebasing with
  the first commit of a repo and the --root flag seems to work fine.

**Comment by tarsius** [comment]
I'm gonna perform the merges today. @kyleam, please don't push to `master` until I have come back here to say I am done.

**Comment by tarsius** [comment]
I am done for today.

**Comment by tarsius** [comment]
*Extracted from the top post.*

I intend to delay merging feature branch into `master` longer than before and to implement no features directly on `master`. This will make it possible to create subminor releases shortly after fixing bugs (which should be done on `master`). Previously this was not possible because `master` also contained unfinished new features. Cleanup should still be done directly on `master`, especially documentation fixes. @kyleam @npostavs push your fixup commits to the respective feature branch, I will take care of squashing them.

For those users who would like to use all new features as soon as they are ready, I will maintain a `pu` branch. That branch will frequently be recreated to incorporate fixup commits. So you should always base your work on `master` or if it depends on changes in a feature branch on that instead.

Note that the feature branches will also frequently be rewritten (in order to incorporate fixup commits, but possibly also to rebase onto `master`), but it should usually be trivial to deal with that using `rr <OTHER-FEATURE> RET`.

When opening a pr for a feature branch, then always do so against `master`, even when the feature branch depends on another feature branch (but if that is so then mention it in the pr).

We'll see how that plays out but at least until v2.3 that's what we do.

**Comment by tarsius** [comment]
Sorry for all the breakage this week.

**Comment by tarsius** [comment]
@kyleam @npostavs I will take a break in November. At least for the first three weeks or possibly for the whole month I will only show up once a week or so. During that time you should only fix bugs on `master` and use feature branches or `next` (or maybe even `pu`) for new features. Really minor non-bugfix changes might also be okay occasionally, but limit yourself to stuff that is suitable for a subminor release. Use your own judgment, or mail me if you need my input (also if you have other questions).

I would also like to release `v2.3.0` tomorrow, or if that doesn't work out the day after that. There are two issues remaining that should be addressed before then: #2357 and #2364. In both cases one of you has taken the lead and if you feel that the proposed changes are suitable, then I'll trust your judgment. I am not sure these fixes are needed because I don't fully understand what the issues are, but it seems safe to apply the fixes - they might turn out to be unnecessary, but I think they won't cause any harm in their current form.

Thanks for you help! And let me know if you have any concerns about me disappearing for a while, now or while I am on break.

**Comment by tarsius** [comment]
All done now. I won't release until Friday so that regressions have a change to bubble up and so that I can do some minor cleanup.
