### ISSUE TITLE
Magit issues on the Spacemacs issue tracker

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2734]
* [x] syl20bnr/spacemacs#6668 Spacemacs losing key binding for discard region in magit with Vim/Hybrid mode

  Support.

* [x] syl20bnr/spacemacs#5802 Magit "y" binding (magit-show-refs) is provided in magit "?" popup, but unusable

  Behaves as intended by `evil-magit` maintainer. I also provided a hint.

* [x] syl20bnr/spacemacs#5384 Viewing magit log for single file prevents viewing log for entire branch
* [x] syl20bnr/spacemacs#4362 When window recentering while region-staging in magit one loses selection

  Behaves as intended.

* [x] syl20bnr/spacemacs#3809 magit-blame and micro-state key display

  Is an `evil-magit` issue.

* [x] syl20bnr/spacemacs#2172 magit-next create branch the powerline mode line branch name doesn't update
* [x] syl20bnr/spacemacs#2086 github layer: magit keys missing from the magit help

  Pending at least sigma/magit-gh-pulls#96.

When an issue is marked as done above, then that doesn't necessarily mean that it has been closed upstream yet. It only means that I am done with it.

**Comment by tarsius** [comment]
Looks like none of that is due to a bug in Magit.
