### ISSUE TITLE
Planned spin-offs and new packages

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2956]
Ever since I became maintainer I have been trying to decouple theoretically independent parts of Magit in practice too.  At first this was mostly done to reduced accidental complexity, but now another major goal is to make parts of Magit reusable by other packages.

Given this new goal, it is necessary that these parts can be distributed as separate packages - I wouldn't want third-party packages that have nothing to do with Git to have to depend on Magit.

For two libraries/packages I have already done that in the past.  They are:

- [`with-editor`](https://melpa.org/#/with-editor)
- [`magit-popup`](https://melpa.org/#/magit-popup)

Both packages now are used by (only) a few third-party packages.  Having lots of other packages use these spin-offs never was the goal anyway, only to make it possible for other packages to do so if there already is desire to do so.  (For the new packages mentioned below, this does not apply.  With those I have bigger plans and hope that they will be used by many third-party packages.)

But separating some feature so clearly that it can be distributed as an independent package has benefits for Magit itself too. I.e. a clean API becomes necessary when exposing a feature to other packages, while before that step it was just something that "really needs to be done", but always got delayed.

---

Without further ado, here's the list of packages I intend to create.  Each of these packages I will also describe individually in separate issues, so don't expect too much depth here.

- [x] #2957 "A successor to `magit-popup`".  Oh boy, I have been talking about that one forever.  `magit-popup` has a number of major issues, which make it desirable to start from scratch, which was the plan all along and isn't surprising considering that it was intended as a temporary solution right from the start.

  The working title is **`transient.el`**, but that I will probably only use that for the core part, which provides an alternative to prefix arguments in the form of infix arguments (and be implemented using similar techniques).  I don't know yet what I will call the object oriented part that will be build on top of that, but it will be a lot like `hydra` and `magit-popup`, just more flexible and composable.

- [ ] #2958 A number of Git related packages, including Magit, allow visiting blobs in a buffer.  These buffers are a lot like file-visiting buffers, except they are not.  The result is that the buffers created by one of these packages is only barely useful for that package that created them and not compatible with any of the other packages.

  This can be fixed by turning blob-visiting buffers into actual file-visiting buffers.  That doesn't mean that a file has to be created, it only means that a *file-handler* has to be defined, a feature provided by Emacs which was originally implemented to allow accessing remote files *as if they were local files*.  In the case of blobs, a file-handler would allow accessing past versions of a file *as if it was the current version*.

  This file-handler will likely be called just **`git-blob-handler.el`**.

- [ ] #2959 Magit is slow and part of fixing that is to use [`libgit2`](https://libgit2.github.com/), "a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language which supports C bindings."  Unfortunately nobody has written that for Elisp yet and since improving performance is a top priority now, I'll to it.

  This will be named just `libgit.el` (or `libgit2.el`) and be pretty basic, i.e. just expose the functions provided by `libgit2` to Elisp.

- [ ] Based on that (in parts) I also intend to create another library (working title **`kit.el`**) that uses `libgit.el` but also provides a lot of convenience features tailored to what Git-related Emacs packages commonly have to do.  For example, while `libgit.el` will certainly provide a function that returns a list of tags, `kit.el` will also contain a function that lets the user select a tag...

  ...and a variable that remembers past choices.  I think it would be highly beneficial if independent git-related packages shared some basic utilities like this.  To some extend the `magit-git.el` could already be used for this purpose, but it doesn't surprise me at all that it isn't used by more third-party packages.  It is fairly disorganized, tailored to Magit's needs, and certainly does not provide a stable API (though breaking changes were very few last years, I believe).

- [x] And finally **sections**.  Like I used to be for *popups*, I am occasionally asked to provide that as an independent package, and agree that doing so would be a good move.

  However before doing so this has to be refactored a lot.  Like for popups I intend to use Eieio (Emacs' Clos implementation).

  The current section implementation has its wards and that was okay for Magit itself until now, but using the current implementation effectively requires too much knowledge about its short-comings for me to comfortably recommend its use in other packages.

  The biggest problem of the current implementation is that it assumes that all sections in a buffer are created at once, in sequential order, and then never modified.  There are some places in Magit where that is not the case, but those uses are hacks.  This is a major issue for Magit itself; it is one of the reasons it isn't faster, as it makes it nearly impossible to calculate section content asynchronously or to only update the contents of sections that actually need to be updated.

**Comment by phil-s** [comment]
Personally I'd love to see general-purpose libraries in GNU ELPA with copyright assignment, so that there's a chance for future Emacs versions to incorporate them (and https://www.reddit.com/r/emacs/comments/5na4wv/x/dc9zsnx/ indicates that in future it will be simpler for ELPA packages to be included in Emacs).

If you're writing a library as new code from scratch then of course you don't have to retrospectively check prior contributors, so it's not much hassle to get started.

Obviously it's your decision, and you've probably at least considered the notion already, but I just wanted to put the idea out there.

**Comment by tarsius** [comment]
@phil-s That's the plan, more or less. In the past, adding Magit itself to GNU Elpa or Emacs has come up a few times. My position always was that I am open to the idea, but that I would want to do it piece by piece, i.e. by adding those parts first that would actually be useful to other packages. Of course these parts have to be created/separated first, and my plans to do that is what I am announcing here ;-)

**Comment by phil-s** [comment]
[Brilliant news](https://lists.gnu.org/archive/html/emacs-devel/2020-04/msg01829.html).  Thank you @tarsius :+1:
